version: '3.8'

networks:
  bridge:

services:
  app:
    image: sample_app:latest
    command: sh -c 'until nc -z db 5432; do sleep 1; done; ./main'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    depends_on:
      - db
    ports:
      - "8181:8181"
    networks:
      - bridge
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    networks:
      - bridge
