name: Build and Push eCom App Image to GCP

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: test-app
  IMAGE_TAG: 1.0
  DOCKER_HUB_USER: chazool
  DOCKER_HUB_TOKEN: 123

jobs:
  build-push-docker-hub:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 #runner
    - name: Build the Docker image
      run: |
          echo "Start Docker building...."
          docker build -t $IMAGE_NAME --file project/Dockerfile.
          echo "completed Docker building...."
          docker images
          docker image tag $IMAGE_NAME $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG
          docker images