name: Build and Push eCom App Image to GCP

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: test-app
  IMAGE_TAG: 1.0
  DOCKER_HUB_USER: ${{ env.DOCKER_HUB_USER_NAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-push-docker-hub:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 #runner
    - name: Build the Docker image
      run: |
          echo $DOCKER_HUB_USER       
          echo "Start Docker building...."
          cd project
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          echo "completed Docker building...."
          docker images
          docker image tag $IMAGE_NAME:$IMAGE_TAG $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG
          docker images
          echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USER --password-stdin            
          docker push chazool/app